create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  code text not null unique,
  file_name text not null,
  cloud_path text not null,
  file_size bigint not null default 0,
  uploader_id bigint,
  downloads integer not null default 0,
  status text not null default 'active'
);

create index if not exists resources_code_idx on public.resources(code);
create index if not exists resources_file_name_idx on public.resources(file_name);
create index if not exists resources_created_at_idx on public.resources(created_at desc);

alter table public.resources disable row level security;
