create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  code text not null,
  sort_order integer not null default 0,
  file_name text not null,
  cloud_path text not null,
  file_size bigint not null default 0,
  uploader_id bigint,
  downloads integer not null default 0,
  status text not null default 'active'
);

create index if not exists resources_code_idx on public.resources(code);
create index if not exists resources_code_sort_idx on public.resources(code, sort_order);
create index if not exists resources_file_name_idx on public.resources(file_name);
create index if not exists resources_created_at_idx on public.resources(created_at desc);

alter table public.resources disable row level security;

-- 旧版本的 code 是唯一值；批量上传需要允许一个取件码对应多个文件。
alter table public.resources drop constraint if exists resources_code_key;


alter table public.resources add column if not exists sort_order integer not null default 0;


-- 机器人运行配置：保存中转群/频道等设置，无需写入 Render 环境变量。
create table if not exists public.bot_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.bot_settings disable row level security;
grant all privileges on table public.bot_settings to service_role;
